name: UnlimitedWaterBucket
version: '${project.version}'
main: me.bingka.unlimitedwaterbucket.UnlimitedWaterBucket
api-version: '1.20'

commands:
  unliwater:
    description: Gives the player an unlimited water bucket
    usage: /unliwater