name: UnlimitedWaterBucket
version: '${project.version}'
main: me.bingka.unlimitedwaterbucket.UnlimitedWaterBucket
api-version: '1.20'

commands:
  unliwater:
    description: Gives the player an unlimited water bucket
    permission: unliwater.givebucket
    permission-message: You don't have permission to run this command.
    usage: /unliwater

permissions:
  unliwater.givebucket:
    description: Allows someone to run the /unliwater command